#!/bin/bash

exec 2>&1
exec \
  envdir ./env \
    sh -c 'exec /usr/local/bin/controller-manager   \
 	--master=127.0.0.1:8080 \
 	--logtostderr=true
	'

	--allocate-node-cidrs=true \
	--cluster-cidr=10.0.0.0/16 \
