#!/bin/bash

exec 2>&1
exec \
  envdir ./env \
    sh -c 'exec /usr/local/bin/controller-manager   \
 	--master=172.16.1.101:8080 \
	--allocate-node-cidrs=true \
	--cluster-cidr=10.10.0.0/16 \
 	--logtostderr=true
	'

