#!/bin/bash

exec 2>&1
exec \
  envdir ./env \
    sh -c 'exec /usr/local/bin/apiserver \
 	--insecure-bind-address=0.0.0.0 \
 	--insecure-port=8080 \
 	--etcd-servers=http://127.0.0.1:2379 \
	--service-cluster-ip-range=10.254.0.0/16 \
	--service-node-port-range=30000-32767 \
 	--logtostderr=true \
	--admission-control=AlwaysAdmit \
	'

