# Usage:
#  ansible-playbook -i ./hosts ./main.yml -vv
#

- hosts: masters
  remote_user: root

  tasks:

  - apt: update_cache=yes
  - apt: upgrade=yes

  - apt: pkg={{ item }} state=present
    with_items:
      - aptitude

  - unarchive: src=./templates/rootfs_common/usr/local/bin/{{ item }} dest=/usr/local/bin/
    with_items:
      - flanneld.tar.xz
      - etcdctl.tar.xz
      - etcd.tar.xz
      - hyperkube.tar.xz

  - file: src=hyperkube dest=/usr/local/bin/{{ item }} state=link
    with_items:
      - apiserver
      - controller-manager
      - scheduler
      - federation-apiserver
      - federation-controller-manager
      - kubectl
      - kubelet
      - proxy


  - file: path=/usr/service/{{ item }} state=directory mode=0755
    with_items:
      - etcd
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler

  - file: path=/usr/service/{{ item }}/log state=directory mode=0755
    with_items:

  - template: src=./templates/rootfs_master/usr/service/{{ item }}/run dest=/usr/service/{{ item }}/run
    with_items:


  - file: src=/usr/service/{{ item }} dest=/etc/service/{{ item }} state=link
    with_items:
      - etcd
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler


