# Usage:
#  ansible-playbook -i ./hosts ./node.yml -vv
#

- hosts: nodes
  remote_user: root

  vars:
    daemons: [ 'flanneld', 'kubelet', 'proxy' ]
    packages: 
      - apt-transport-https
      - ca-certificates
      - bridge-utils
      - sudo
      - aptitude

  tasks:

  - apt: update_cache=yes
  - apt: upgrade=yes

  - apt: pkg={{ item }} state=present
    with_items:
      - "{{ packages }}"

  - local_action: file path=./PKI state=directory

  - local_action: template src=files/pki/openssl.cnf dest=./PKI/{{ ansible_eth0.ipv4.address }}.cnf
  - local_action: shell openssl genrsa -out ./PKI/{{ ansible_eth0.ipv4.address }}.key 2048
  - local_action: shell openssl req -new -key ./PKI/{{ ansible_eth0.ipv4.address }}.key -subj "/CN={{ ansible_eth0.ipv4.address }}" -out ./PKI/{{ ansible_eth0.ipv4.address }}.csr -config ./PKI/{{ ansible_eth0.ipv4.address }}.cnf
  - local_action: shell openssl x509 -req -in ./PKI/{{ ansible_eth0.ipv4.address }}.csr -CA ./PKI/ca.crt -CAkey ./PKI/ca.key -CAcreateserial -out ./PKI/{{ ansible_eth0.ipv4.address }}.crt -days 10000  -extensions v3_req -extfile ./PKI/{{ ansible_eth0.ipv4.address }}.cnf

  - file: path=/var/lib/kubelet/tls state=directory
  - copy: src=./PKI/ca.crt dest=/var/lib/kubelet/tls/ca.crt mode=0700
  - copy: src=./PKI/{{ ansible_eth0.ipv4.address }}.key dest=/var/lib/kubelet/tls/kubelet.key mode=0700
  - copy: src=./PKI/{{ ansible_eth0.ipv4.address }}.crt dest=/var/lib/kubelet/tls/kubelet.crt mode=0700

  - unarchive: src=./files/common/usr/local/bin/{{ item }} dest=/usr/local/bin/
    with_items:
      - flanneld.tar.xz
      - hyperkube.tar.xz

  - file: src=hyperkube dest=/usr/local/bin/{{ item }} state=link
    with_items:
      - "{{ daemons }}"

  - file: path=/usr/service/{{ item }}/log state=directory mode=0755
    with_items:
      - "{{ daemons }}"

  - template: src=./files/master/usr/service/{{ item }}/run dest=/usr/service/{{ item }}/run mode=0700
    with_items:
      - "{{ daemons }}"

  - template: src=./files/master/usr/service/{{ item }}/log/run dest=/usr/service/{{ item }}/log/run mode=0700
    with_items:
      - "{{ daemons }}"

  - file: path=/etc/service/ state=directory mode=0755
    with_items:
      - "{{ daemons }}"

  - file: src=/usr/service/{{ item }} dest=/etc/service/{{ item }} state=link
    with_items:
      - "{{ daemons }}"

  - apt: pkg={{ item }} state=present
    with_items:
      - daemontools-run

  - shell: 'svc -t /etc/service/* ; sleep 3'

#######################
  - file: path=/etc/apt/sources.list.d/ state=directory mode=0755
  - template: src=files/common/etc/apt/sources.list.d/docker.list  dest=/etc/apt/sources.list.d/docker.list
  - shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

  - apt: update_cache=yes
  - apt: upgrade=yes
  - apt: pkg=docker-engine state=present

  - template: src=files/node/etc/systemd/system/multi-user.target.wants/docker.service dest=/etc/systemd/system/multi-user.target.wants/docker.service
  - shell: systemctl daemon-reload
  - service: state=restarted name=docker

########################


